version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: connect4-server
    restart: unless-stopped
    environment:
      - PORT=80
    ports:
      - "4000:80"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: connect4-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - SERVER_HOST={connect4-server}:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
